"""
Self-contained sentence-wise anonymization + paraphrasing pipeline.

This script has no dependency on local helper modules such as `utils.py`.
Everything required for:
  1) Vec2Text embedding inversion-based anonymization,
  2) sentence-wise processing,
  3) LLM paraphrasing (default: local Ollama HTTP API; optional: Hugging Face in-process)

Default LLM path is Ollama-first: set --llm-backend hf only if you want Transformers
paraphrase models instead of a local Ollama server.

Privacy design follows three layers:
  - Layer 1 (most-sensitive): user-specified information removed in final refinement.
  - Layer 2 (least-sensitive): user-specified releasable keywords guide inversion.
  - Layer 3 (unclear sensitivity): remaining content represented as sentence embedding
    and perturbed with metric-DP style Gaussian noise before inversion.
"""

from __future__ import annotations

import argparse
import copy
import json
import math
import os
import re
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Any, List, Optional, Sequence, Tuple

os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
os.environ["TORCH_SHOW_CPP_STACKTRACES"] = "1"

import torch
import torch.nn.functional as F
import vec2text
from transformers import AutoModelForCausalLM, AutoModelForSeq2SeqLM, AutoTokenizer


# =========================
# Data containers
# =========================


@dataclass
class AnonymizationResult:
    """
    Output of anonymizing one text segment.

    Notes:
    - Embedding tensors are detached and moved to CPU for easier inspection/printing.
    - `mixed_target_embedding` is the exact target embedding passed to the inverter.
    """

    anonymized_text: str
    mixed_target_embedding: torch.Tensor  # shape: (1, D)
    noisy_embedding: torch.Tensor  # shape: (1, D)
    clean_embedding: torch.Tensor  # shape: (1, D)
    keyword_embeddings: Optional[torch.Tensor] = None  # shape: (K, D)


@dataclass
class SentenceWiseAnonymizationResult:
    """
    Output of sentence-wise anonymization.

    The final anonymized text is generated by joining sentence outputs using '. '.
    """

    anonymized_text: str
    sentence_results: List[AnonymizationResult]
    source_sentences: List[str]


@dataclass
class ParaphraseResult:
    """Output of the open-source paraphrasing stage."""

    model_name: str
    model_type: str  # "seq2seq" or "causal"
    input_text: str
    paraphrased_text: str


@dataclass
class PrivacyAccountantResult:
    """
    Privacy cost estimate for sentence-level Gaussian perturbations.

    This accountant uses a zCDP composition view and converts to (epsilon, delta)-DP:
      rho_single = sensitivity^2 / (2 * sigma^2)
      rho_total  = num_releases * rho_single
      epsilon    = rho_total + 2 * sqrt(rho_total * log(1/delta))
    """

    num_releases: int
    sigma: float
    delta: float
    sensitivity: float
    rho_single: float
    rho_total: float
    epsilon: float


@dataclass
class PreprocessedPrivacyText:
    """Text after deterministic scrub and slot-preserving preprocessing."""

    original_text: str
    scrubbed_text: str
    residual_text: str
    expanded_removal_targets: List[str]
    preserved_keywords: List[str]
    safe_task_keywords: List[str]
    safe_location_keywords: List[str]
    safe_preference_keywords: List[str]
    residual_segments: List[str]


# =========================
# Parsing helpers
# =========================


def parse_keyword_list(raw_keywords: Optional[str]) -> List[str]:
    """Parse comma-separated keywords into a clean list."""
    if not raw_keywords or not raw_keywords.strip():
        return []
    return [part.strip() for part in raw_keywords.split(",") if part.strip()]


def parse_model_list(raw_models: Optional[str]) -> List[str]:
    """Parse comma-separated model names into a clean list."""
    if not raw_models or not raw_models.strip():
        return []
    return [part.strip() for part in raw_models.split(",") if part.strip()]


def parse_removal_list(raw_removals: Optional[str]) -> List[str]:
    """Parse comma-separated removal targets into a clean list."""

    if not raw_removals or not raw_removals.strip():
        return []
    return [part.strip() for part in raw_removals.split(",") if part.strip()]


def normalize_whitespace(text: str) -> str:
    """Collapse repeated whitespace without changing sentence punctuation."""

    return re.sub(r"\s+", " ", text).strip()


def dedupe_preserve_order(values: Sequence[str]) -> List[str]:
    """Deduplicate string values while preserving their order."""

    seen = set()
    output: List[str] = []
    for value in values:
        cleaned = value.strip()
        if not cleaned:
            continue
        lowered = cleaned.lower()
        if lowered in seen:
            continue
        seen.add(lowered)
        output.append(cleaned)
    return output


def regex_sub_with_placeholder(text: str, pattern: str, placeholder: str) -> str:
    """Replace regex matches with a stable placeholder token."""

    return re.sub(pattern, placeholder, text, flags=re.IGNORECASE)


def expand_category_removal_targets(text: str, removal_targets: List[str]) -> List[str]:
    """
    Expand category-level removal requests into concrete or typed targets.

    The downstream scrubber understands the bracketed typed placeholders below.
    """

    expanded: List[str] = []
    for target in removal_targets:
        lowered = target.strip().lower()
        if not lowered:
            continue
        if lowered in {"all names", "names", "name"}:
            expanded.append("[PERSON]")
            continue
        if lowered in {"all ages", "ages", "age"}:
            expanded.append("[AGE]")
            continue
        if lowered in {
            "all employers",
            "employers",
            "employer",
            "company",
            "all companies",
            "organization",
            "all organizations",
        }:
            expanded.append("[ORG]")
            continue
        if lowered in {
            "all addresses",
            "address",
            "all locations",
            "location",
            "all neighborhoods",
            "neighborhood",
        }:
            expanded.append("[LOCATION]")
            continue
        expanded.append(target)
    return dedupe_preserve_order(expanded)


def infer_placeholder_for_target(target: str) -> str:
    """
    Pick a generic placeholder token for a removal target.

    Heuristic mapping:
    - person-like names -> "someone"
    - location-like terms -> "somewhere"
    - default -> "something"
    """

    t = target.strip()
    if not t:
        return "something"

    # Simple person-name heuristic: 2+ title-cased words (e.g., "John Smith").
    words = [w for w in re.split(r"\s+", t) if w]
    if len(words) >= 2 and all(re.match(r"^[A-Z][a-zA-Z'-]*$", w) for w in words):
        return "someone"

    # Location-like hints for common place words/abbreviations.
    lower = t.lower()
    location_hints = {
        "city",
        "town",
        "village",
        "neighborhood",
        "neighbourhood",
        "flat",
        "apartment",
        "street",
        "road",
        "avenue",
        "district",
        "country",
        "state",
        "london",
        "uk",
        "u.k.",
        "england",
        "usa",
        "u.s.",
        "u.s.a.",
        "europe",
        "asia",
        "africa",
    }
    if any(hint in lower for hint in location_hints):
        return "somewhere"

    location_suffixes = ("ditch", "ham", "ton", "ford", "bury", "bridge", "field", "side")
    if len(words) == 1 and lower.endswith(location_suffixes):
        return "somewhere"

    return "something"


def replace_targets_literal(text: str, removal_targets: List[str]) -> str:
    """
    Replace target phrases directly in text (case-insensitive), preserving structure.
    """

    updated = text
    for target in removal_targets:
        target_clean = target.strip()
        if not target_clean:
            continue
        if target_clean == "[AGE]":
            updated = regex_sub_with_placeholder(
                updated,
                r"\b(?:age\s*\d{1,3}|\d{1,3}\s*(?:years old|year-old)|i\s*[\'’]?m\s*\d{1,3})\b",
                "[AGE]",
            )
            continue
        if target_clean == "[PERSON]":
            updated = re.sub(
                r"\b(?:[A-Z][a-z]+(?:\s+[A-Z][a-z]+)+)\b",
                "[PERSON]",
                updated,
            )
            continue
        if target_clean == "[ORG]":
            updated = re.sub(
                r"\b(?:[A-Z][\w&'-]+(?:\s+[A-Z][\w&'-]+){0,3}\s+(?:Inc|LLC|Ltd|Corp|Company|Studio|Agency|Enterprises))\b",
                "[ORG]",
                updated,
            )
            continue
        if target_clean == "[LOCATION]":
            updated = re.sub(
                r"\b(?:flat|apartment|suite|room)?\s*\d+\s+[A-Z][\w'-]+(?:\s+[A-Z][\w'-]+){0,3}\b",
                "[LOCATION]",
                updated,
            )
            updated = re.sub(
                r"\b(?:[A-Z][a-z]+(?:ditch|ham|ton|ford|bury|bridge|field|side))\b",
                "[LOCATION]",
                updated,
            )
            continue
        placeholder = infer_placeholder_for_target(target_clean)
        pattern = re.compile(re.escape(target_clean), flags=re.IGNORECASE)
        updated = pattern.sub(placeholder, updated)
    return updated


def split_sentences_by_period(text: str) -> List[str]:
    """
    Split into sentence-like spans with simple punctuation-aware heuristics.
    """

    normalized = normalize_whitespace(text)
    if not normalized:
        return []
    parts = re.split(r"(?<=[.!?])\s+|\n+", normalized)
    return [part.strip() for part in parts if part.strip()]


def chunk_sentences_for_privacy(sentences: Sequence[str], max_chunks: int) -> List[str]:
    """Combine neighboring sentences to limit the number of DP releases."""

    items = [s.strip() for s in sentences if s and s.strip()]
    if not items:
        return []
    if max_chunks <= 0 or len(items) <= max_chunks:
        return list(items)

    chunk_size = max(1, math.ceil(len(items) / max_chunks))
    chunks: List[str] = []
    for start in range(0, len(items), chunk_size):
        chunk = " ".join(items[start : start + chunk_size]).strip()
        if chunk:
            chunks.append(chunk)
    return chunks[:max_chunks] if len(chunks) > max_chunks else chunks


def classify_public_keywords(keywords: Sequence[str]) -> Tuple[List[str], List[str], List[str]]:
    """Split keywords into task/location/preference buckets."""

    task_keywords: List[str] = []
    location_keywords: List[str] = []
    preference_keywords: List[str] = []
    for keyword in dedupe_preserve_order(list(keywords)):
        lower = keyword.lower()
        if lower in {"uk", "u.k.", "england", "london"}:
            location_keywords.append(keyword)
        elif any(token in lower for token in ("restaurant", "dining", "food", "cafe", "bar")):
            task_keywords.append(keyword)
        else:
            preference_keywords.append(keyword)
    return task_keywords, location_keywords, preference_keywords


def placeholder_for_safe_keyword(keyword: str) -> str:
    """Return a stable placeholder bucket for a preserved public keyword."""

    task_keywords, location_keywords, _ = classify_public_keywords([keyword])
    if location_keywords:
        return "[SAFE_LOCATION]"
    if task_keywords:
        return "[SAFE_TASK]"
    return "[SAFE_PREFERENCE]"


def strip_safe_slot_placeholders(text: str) -> str:
    """Drop safe-slot placeholders from residual summaries before final rendering."""

    cleaned = re.sub(r"\[SAFE_[A-Z_]+\]", "", text)
    cleaned = re.sub(r"\s+([,.;:!?])", r"\1", cleaned)
    return normalize_whitespace(cleaned)


def restore_safe_slot_placeholders(
    text: str,
    *,
    safe_task_keywords: Sequence[str],
    safe_location_keywords: Sequence[str],
    safe_preference_keywords: Sequence[str],
) -> str:
    """Restore safe-slot placeholders using canonical preserved values."""

    restored = text
    task_value = safe_task_keywords[0] if safe_task_keywords else ""
    preference_value = safe_preference_keywords[0] if safe_preference_keywords else ""
    location_value = ""
    if safe_location_keywords:
        generic_locations = {"uk", "u.k.", "england"}
        specific_locations = [
            value for value in safe_location_keywords if value.strip().lower() not in generic_locations
        ]
        location_value = (specific_locations or list(safe_location_keywords))[0]
    replacements = {
        "[SAFE_TASK]": task_value,
        "[SAFE_LOCATION]": location_value,
        "[SAFE_PREFERENCE]": preference_value,
    }
    for placeholder, value in replacements.items():
        if value:
            restored = restored.replace(placeholder, value)
        else:
            restored = restored.replace(placeholder, "")
    restored = re.sub(r"\s+([,.;:!?])", r"\1", restored)
    restored = re.sub(r"\b(a)\s+([aeiouAEIOU])", r"an \2", restored)
    return normalize_whitespace(restored)


def redact_preserved_keywords_from_residual(text: str, keywords: Sequence[str]) -> str:
    """
    Replace explicitly allowed public keywords with stable placeholders.

    This keeps those slots out of the DP-protected residual path while allowing
    the final renderer to re-introduce them deterministically.
    """

    redacted = text
    sorted_keywords = sorted(
        dedupe_preserve_order(list(keywords)),
        key=lambda keyword: len(keyword),
        reverse=True,
    )
    for keyword in sorted_keywords:
        if not keyword.strip():
            continue
        placeholder = placeholder_for_safe_keyword(keyword)
        redacted = re.sub(
            re.escape(keyword),
            placeholder,
            redacted,
            flags=re.IGNORECASE,
        )
    return normalize_whitespace(redacted)


def preprocess_privacy_text(
    text: str,
    *,
    keywords: Sequence[str],
    removal_targets: Sequence[str],
    max_privacy_chunks: int,
) -> PreprocessedPrivacyText:
    """
    Deterministically scrub explicit sensitive spans before embedding inversion.

    Keywords are intentionally preserved as public utility slots and are not
    counted inside the DP mechanism.
    """

    expanded_targets = expand_category_removal_targets(text, list(removal_targets))
    scrubbed = replace_targets_literal(text, expanded_targets)
    scrubbed = normalize_whitespace(scrubbed)
    preserved_keywords = dedupe_preserve_order(list(keywords))
    safe_task_keywords, safe_location_keywords, safe_preference_keywords = classify_public_keywords(
        preserved_keywords
    )
    residual_text = redact_preserved_keywords_from_residual(scrubbed, preserved_keywords)
    residual_segments = chunk_sentences_for_privacy(
        split_sentences_by_period(residual_text),
        max_chunks=max_privacy_chunks,
    )
    residual_joined = " ".join(residual_segments).strip()
    return PreprocessedPrivacyText(
        original_text=text,
        scrubbed_text=scrubbed,
        residual_text=residual_joined,
        expanded_removal_targets=expanded_targets,
        preserved_keywords=preserved_keywords,
        safe_task_keywords=safe_task_keywords,
        safe_location_keywords=safe_location_keywords,
        safe_preference_keywords=safe_preference_keywords,
        residual_segments=residual_segments,
    )


def estimate_metric_dp_privacy_cost(
    *,
    num_releases: int,
    sigma: float,
    delta: float,
    sensitivity: float = 1.0,
) -> PrivacyAccountantResult:
    """
    Estimate overall privacy cost for sentence-level metric-DP perturbation.

    Assumptions:
    - One Gaussian perturbation release per sentence.
    - Same sigma used for every sentence.
    - L2 sensitivity of embedding function is provided by user (default 1.0).
    - Composition handled via zCDP, then converted to (epsilon, delta)-DP.
    """

    releases = max(0, int(num_releases))
    s = float(sensitivity)
    sig = float(sigma)
    d = float(delta)

    if d <= 0.0 or d >= 1.0:
        raise ValueError("dp-delta must be in (0, 1).")
    if s <= 0.0:
        raise ValueError("dp-sensitivity must be > 0.")

    if releases == 0:
        return PrivacyAccountantResult(
            num_releases=0,
            sigma=sig,
            delta=d,
            sensitivity=s,
            rho_single=0.0,
            rho_total=0.0,
            epsilon=0.0,
        )

    if sig <= 0.0:
        # No noise => no finite DP guarantee.
        return PrivacyAccountantResult(
            num_releases=releases,
            sigma=sig,
            delta=d,
            sensitivity=s,
            rho_single=float("inf"),
            rho_total=float("inf"),
            epsilon=float("inf"),
        )

    rho_single = (s * s) / (2.0 * sig * sig)
    rho_total = float(releases) * rho_single
    epsilon = rho_total + 2.0 * math.sqrt(rho_total * math.log(1.0 / d))

    return PrivacyAccountantResult(
        num_releases=releases,
        sigma=sig,
        delta=d,
        sensitivity=s,
        rho_single=rho_single,
        rho_total=rho_total,
        epsilon=epsilon,
    )


# =========================
# Vec2Text core utilities
# =========================


def patch_transformers_constrained_beamsearch_4372() -> None:
    """
    Patch transformers constrained beam-search finalize() for 4.37.2.

    Why this exists:
    Vec2Text generation with constrained decoding can hit:
      RuntimeError: Could not infer dtype of NoneType
    when some hypotheses have `best_idx=None`.
    """

    import transformers
    from collections import UserDict
    from transformers.generation.beam_search import ConstrainedBeamSearchScorer

    if getattr(ConstrainedBeamSearchScorer.finalize, "_vec2text_patched", False):
        return

    if transformers.__version__ != "4.37.2":
        print(
            f"[patch] Warning: transformers=={transformers.__version__}. "
            "Patch was written for 4.37.2."
        )

    def finalize_patched(
        self,
        input_ids: torch.LongTensor,
        final_beam_scores: torch.FloatTensor,
        final_beam_tokens: torch.LongTensor,
        final_beam_indices: torch.LongTensor,
        max_length: int,
        pad_token_id: Optional[int] = None,
        eos_token_id: Optional[int | List[int]] = None,
        beam_indices: Optional[torch.LongTensor] = None,
        decoder_prompt_len: int = 0,
    ) -> Any:
        batch_size = len(self._beam_hyps)
        if isinstance(eos_token_id, int):
            eos_token_id = [eos_token_id]

        for batch_idx, beam_hyp in enumerate(self._beam_hyps):
            if self._done[batch_idx]:
                continue

            ids_collect: List[int] = []
            for beam_id in range(self.num_beams):
                batch_beam_idx = batch_idx * self.num_beams + beam_id
                final_score = final_beam_scores[batch_beam_idx].item()
                final_tokens = input_ids[batch_beam_idx]
                completes_constraint = self.check_completes_constraints(
                    final_tokens.cpu().tolist()
                )
                if completes_constraint:
                    beam_index = beam_indices[batch_beam_idx] if beam_indices is not None else None
                    generated_len = final_tokens.shape[-1] - decoder_prompt_len
                    beam_hyp.add(
                        final_tokens,
                        final_score,
                        beam_indices=beam_index,
                        generated_len=generated_len,
                    )
                    ids_collect.append(beam_id)

            if len(ids_collect) < self.num_beam_hyps_to_keep:
                for beam_id in range(self.num_beams):
                    if beam_id not in ids_collect:
                        batch_beam_idx = batch_idx * self.num_beams + beam_id
                        final_score = final_beam_scores[batch_beam_idx].item()
                        final_tokens = input_ids[batch_beam_idx]
                        generated_len = final_tokens.shape[-1] - decoder_prompt_len
                        beam_hyp.add(final_tokens, final_score, generated_len=generated_len)
                    if len(ids_collect) >= self.num_beam_hyps_to_keep:
                        break

        sent_lengths = input_ids.new(batch_size * self.num_beam_hyps_to_keep)
        best: List[torch.LongTensor] = []
        best_indices: List[Optional[Sequence[int]]] = []
        best_scores = torch.zeros(
            batch_size * self.num_beam_hyps_to_keep,
            device=self.device,
            dtype=torch.float32,
        )

        for i, beam_hyp in enumerate(self._beam_hyps):
            sorted_hyps = sorted(beam_hyp.beams, key=lambda x: x[0])
            for j in range(self.num_beam_hyps_to_keep):
                best_hyp_tuple = sorted_hyps.pop()
                best_score = best_hyp_tuple[0]
                best_hyp = best_hyp_tuple[1]
                best_index = best_hyp_tuple[2]

                sent_lengths[self.num_beam_hyps_to_keep * i + j] = len(best_hyp)
                best.append(best_hyp)
                best_indices.append(best_index)
                best_scores[i * self.num_beam_hyps_to_keep + j] = best_score

        sent_lengths_max = sent_lengths.max().item() + 1
        sent_max_len = min(sent_lengths_max, max_length) if max_length is not None else sent_lengths_max
        decoded = input_ids.new(batch_size * self.num_beam_hyps_to_keep, sent_max_len)

        if len(best_indices) > 0 and any(idx is not None for idx in best_indices):
            indices = input_ids.new(batch_size * self.num_beam_hyps_to_keep, sent_max_len)
        else:
            indices = None

        if sent_lengths.min().item() != sent_lengths.max().item():
            if pad_token_id is None:
                raise ValueError("`pad_token_id` has to be defined")
            decoded.fill_(pad_token_id)
            if indices is not None:
                indices.fill_(-1)

        for i, (hypo, best_idx) in enumerate(zip(best, best_indices)):
            decoded[i, : sent_lengths[i]] = hypo
            if indices is not None and best_idx is not None:
                indices[i, : len(best_idx)] = torch.tensor(
                    best_idx,
                    device=indices.device,
                    dtype=indices.dtype,
                )
            if sent_lengths[i] < sent_max_len:
                decoded[i, sent_lengths[i]] = eos_token_id[0]

        return UserDict(
            {
                "sequences": decoded,
                "sequence_scores": best_scores,
                "beam_indices": indices,
            }
        )

    finalize_patched._vec2text_patched = True
    ConstrainedBeamSearchScorer.finalize = finalize_patched
    print("[patch] Patched ConstrainedBeamSearchScorer.finalize() for transformers 4.37.2.")


def load_vec2text_corrector(
    device: str,
    *,
    inversion_model_name: str = "jxm/gtr__nq__32",
    corrector_model_name: str = "jxm/gtr__nq__32__correct",
    cache_dir: Optional[str] = None,
) -> Any:
    """
    Load Vec2Text inversion+corrector pair.

    Returns:
        Corrector object used by vec2text.generate().
    """

    print("Loading vec2text models...")
    inversion_model = vec2text.models.InversionModel.from_pretrained(
        inversion_model_name,
        cache_dir=cache_dir,
    ).to(device)
    corrector_model = vec2text.models.CorrectorEncoderModel.from_pretrained(
        corrector_model_name,
        cache_dir=cache_dir,
    ).to(device)
    corrector = vec2text.load_corrector(inversion_model, corrector_model)
    corrector.inversion_trainer.model.to(device).eval()
    corrector.model.to(device).eval()
    print("Vec2text models loaded.")
    return corrector


@torch.no_grad()
def embed_texts(
    corrector: Any,
    texts: Sequence[str],
    *,
    max_length: int = 128,
    device: str = "cpu",
) -> torch.Tensor:
    """Encode text(s) into the same embedding space used by the vec2text checkpoint."""

    tok = corrector.embedder_tokenizer(
        list(texts),
        return_tensors="pt",
        max_length=max_length,
        truncation=True,
        padding="max_length",
    ).to(device)

    emb = corrector.inversion_trainer.call_embedding_model(
        input_ids=tok.input_ids,
        attention_mask=tok.attention_mask,
    )
    return emb


def add_gaussian_noise(emb: torch.Tensor, noise_std: float, seed: int = 0) -> torch.Tensor:
    """Add isotropic Gaussian noise to an embedding tensor."""

    if noise_std <= 0:
        return emb
    generator = torch.Generator(device="cpu")
    generator.manual_seed(seed)
    noise = torch.randn(emb.shape, generator=generator, dtype=emb.dtype)
    return emb + noise_std * noise.to(emb.device)


def l2_normalize(x: torch.Tensor, eps: float = 1e-12) -> torch.Tensor:
    """L2-normalize each row vector."""

    return x / torch.clamp(x.norm(p=2, dim=-1, keepdim=True), min=eps)


@torch.no_grad()
def mix_embeddings(
    base_embedding: torch.Tensor,
    keyword_embeddings: torch.Tensor,
    *,
    keyword_weights: Optional[List[float]] = None,
    keyword_total_weight: float = 0.35,
    normalize_each: bool = True,
    normalize_output: bool = True,
) -> Tuple[torch.Tensor, float, torch.Tensor]:
    """
    Mix noisy base embedding and keyword embeddings.

    Formula:
        e_mix = normalize(w_base * norm(e_base) + sum_k w_k * norm(e_kw_k))
    """

    if base_embedding.dim() != 2 or base_embedding.shape[0] != 1:
        raise ValueError("base_embedding must have shape (1, D)")
    if keyword_embeddings.dim() != 2 or keyword_embeddings.shape[0] < 1:
        raise ValueError("keyword_embeddings must have shape (K, D), K>=1")
    if base_embedding.shape[1] != keyword_embeddings.shape[1]:
        raise ValueError("base and keyword embeddings must have the same dimension")

    k_count = keyword_embeddings.shape[0]
    dev = base_embedding.device
    dtype = base_embedding.dtype

    if keyword_weights is None:
        w_kw = torch.full(
            (k_count,),
            float(keyword_total_weight) / float(k_count),
            device=dev,
            dtype=dtype,
        )
    else:
        if len(keyword_weights) != k_count:
            raise ValueError(f"keyword_weights length {len(keyword_weights)} != K={k_count}")
        w_kw = torch.tensor(keyword_weights, device=dev, dtype=dtype)

    w_kw_sum = float(w_kw.sum().item())
    if w_kw_sum > 1.0 + 1e-6:
        raise ValueError(f"Sum(keyword_weights)={w_kw_sum:.4f} > 1.0")
    w_base = 1.0 - w_kw_sum

    base_part = l2_normalize(base_embedding) if normalize_each else base_embedding
    kw_part = l2_normalize(keyword_embeddings) if normalize_each else keyword_embeddings
    kw_sum = (w_kw[:, None] * kw_part).sum(dim=0)
    mixed = w_base * base_part + kw_sum.unsqueeze(0)

    if normalize_output:
        mixed = l2_normalize(mixed)

    return mixed, w_base, w_kw


def optimize_joint_target_embedding(
    noisy_embedding: torch.Tensor,
    keyword_embeddings: Optional[torch.Tensor],
    *,
    keyword_total_weight: float,
    num_steps: int = 80,
    learning_rate: float = 0.1,
) -> torch.Tensor:
    """
    Explicitly optimize the inversion target embedding with a joint cosine objective.

    Objective:
      maximize (1-lambda) * cos(z, noisy) + lambda * mean_k cos(z, kw_k)
    where lambda = keyword_total_weight.

    Notes:
    - If no keywords are provided, this returns normalized noisy embedding.
    - This is a train-free optimization in embedding space only.
    """

    # Clamp lambda to a valid convex trade-off range.
    lambda_kw = max(0.0, min(1.0, float(keyword_total_weight)))

    # If no keyword info is available, target should stay aligned with noisy embedding.
    if keyword_embeddings is None or keyword_embeddings.numel() == 0 or lambda_kw <= 0.0:
        return l2_normalize(noisy_embedding)

    noisy_ref = l2_normalize(noisy_embedding.detach())
    kw_ref = l2_normalize(keyword_embeddings.detach())

    # Start from noisy embedding and optimize z directly.
    z = noisy_embedding.detach().clone().requires_grad_(True)
    optimizer = torch.optim.Adam([z], lr=float(learning_rate))

    for _ in range(max(1, int(num_steps))):
        optimizer.zero_grad(set_to_none=True)
        z_norm = l2_normalize(z)

        cos_noisy = F.cosine_similarity(z_norm, noisy_ref, dim=-1).mean()
        cos_keywords = F.cosine_similarity(
            kw_ref, z_norm.expand_as(kw_ref), dim=-1
        ).mean()
        objective = (1.0 - lambda_kw) * cos_noisy + lambda_kw * cos_keywords

        loss = -objective
        loss.backward()
        optimizer.step()

    return l2_normalize(z.detach())


@torch.no_grad()
def invert_vec2text(
    corrector: Any,
    embedding_1xD: torch.Tensor,
    *,
    num_steps: int = 40,
    sequence_beam_width: int = 0,
    min_length: Optional[int] = None,
    max_length: Optional[int] = None,
    must_include_phrases: Optional[List[str]] = None,
    num_beams: int = 6,
) -> str:
    """Decode an embedding back to text using vec2text."""

    embedding_1xD = embedding_1xD.to(next(corrector.model.parameters()).device)

    generation_kwargs = copy.copy(getattr(corrector, "gen_kwargs", {}))
    generation_kwargs["do_sample"] = False
    generation_kwargs["early_stopping"] = False

    if min_length is not None:
        generation_kwargs["min_length"] = int(min_length)
    if max_length is not None:
        generation_kwargs["max_length"] = int(max_length)

    if must_include_phrases:
        generation_kwargs["num_beams"] = max(int(num_beams), 2)
        force_words_ids: List[List[int]] = []
        for phrase in must_include_phrases:
            token_ids = corrector.tokenizer(phrase, add_special_tokens=False).input_ids
            if len(token_ids) == 0:
                raise ValueError(f"Phrase tokenized to empty list: {phrase!r}")
            force_words_ids.append(token_ids)
        generation_kwargs["force_words_ids"] = force_words_ids
    else:
        generation_kwargs["num_beams"] = 1

    corrector.return_best_hypothesis = sequence_beam_width > 0

    generated_ids = corrector.generate(
        inputs={"frozen_embeddings": embedding_1xD},
        generation_kwargs=generation_kwargs,
        num_recursive_steps=num_steps,
        sequence_beam_width=sequence_beam_width,
    )
    return corrector.tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]


def cosine_sim(a: torch.Tensor, b: torch.Tensor) -> float:
    """Compute cosine similarity between two same-shape vectors/tensors."""

    return float(F.cosine_similarity(a, b, dim=-1).item())


def cos_to_keywords(
    recovered_emb: torch.Tensor,
    keyword_embs: Optional[torch.Tensor],
) -> Tuple[float, float]:
    """Return mean/max cosine similarity from recovered embedding to keyword embeddings."""

    if keyword_embs is None or keyword_embs.numel() == 0:
        return float("nan"), float("nan")
    sims = F.cosine_similarity(keyword_embs, recovered_emb.expand_as(keyword_embs), dim=-1)
    return float(sims.mean().item()), float(sims.max().item())


# =========================
# Anonymization pipeline
# =========================


def anonymize_localized(
    private_text: str,
    keywords: List[str],
    sigma: float,
    corrector: Any,
    *,
    device: str = "cpu",
    keyword_total_weight: float = 0.35,
    noise_seed: int = 0,
    embed_max_length: int = 128,
    keyword_embed_max_length: int = 32,
    num_steps: int = 40,
    sequence_beam_width: int = 0,
    min_length: Optional[int] = 6,
    max_length: Optional[int] = 40,
    joint_opt_steps: int = 80,
    joint_opt_lr: float = 0.1,
) -> AnonymizationResult:
    """
    Anonymize one text segment by optimizing a joint embedding objective, then inverting.
    """

    clean = embed_texts(corrector, [private_text], max_length=embed_max_length, device=device)
    noisy = add_gaussian_noise(clean, noise_std=float(sigma), seed=int(noise_seed))

    cleaned_keywords = [k.strip() for k in keywords if k and k.strip()]
    keyword_embs: Optional[torch.Tensor] = None
    target_embedding = l2_normalize(noisy)
    if len(cleaned_keywords) > 0:
        keyword_embs = embed_texts(
            corrector,
            cleaned_keywords,
            max_length=keyword_embed_max_length,
            device=device,
        )
        target_embedding = optimize_joint_target_embedding(
            noisy_embedding=noisy,
            keyword_embeddings=keyword_embs,
            keyword_total_weight=float(keyword_total_weight),
            num_steps=int(joint_opt_steps),
            learning_rate=float(joint_opt_lr),
        )
    else:
        target_embedding = optimize_joint_target_embedding(
            noisy_embedding=noisy,
            keyword_embeddings=None,
            keyword_total_weight=float(keyword_total_weight),
            num_steps=int(joint_opt_steps),
            learning_rate=float(joint_opt_lr),
        )

    anonymized_text = invert_vec2text(
        corrector,
        target_embedding,
        num_steps=int(num_steps),
        sequence_beam_width=int(sequence_beam_width),
        min_length=min_length,
        max_length=max_length,
        must_include_phrases=None,
    )

    return AnonymizationResult(
        anonymized_text=anonymized_text,
        mixed_target_embedding=target_embedding.detach().cpu(),
        noisy_embedding=noisy.detach().cpu(),
        clean_embedding=clean.detach().cpu(),
        keyword_embeddings=keyword_embs.detach().cpu() if keyword_embs is not None else None,
    )


def anonymize_localized_sentence_wise(
    private_text: str,
    keywords: List[str],
    sigma: float,
    corrector: Any,
    *,
    device: str = "cpu",
    keyword_total_weight: float = 0.35,
    noise_seed: int = 0,
    embed_max_length: int = 128,
    keyword_embed_max_length: int = 32,
    num_steps: int = 40,
    sequence_beam_width: int = 0,
    min_length: Optional[int] = 6,
    max_length: Optional[int] = 40,
    joint_opt_steps: int = 80,
    joint_opt_lr: float = 0.1,
    max_privacy_chunks: int = 3,
) -> SentenceWiseAnonymizationResult:
    """
    Apply localized anonymization to a small number of semantic chunks.
    """

    source_sentences = chunk_sentences_for_privacy(
        split_sentences_by_period(private_text),
        max_chunks=max_privacy_chunks,
    )
    if not source_sentences:
        return SentenceWiseAnonymizationResult(
            anonymized_text="",
            sentence_results=[],
            source_sentences=[],
        )

    sentence_results: List[AnonymizationResult] = []
    for i, sentence in enumerate(source_sentences):
        result = anonymize_localized(
            private_text=sentence,
            keywords=keywords,
            sigma=sigma,
            corrector=corrector,
            device=device,
            keyword_total_weight=keyword_total_weight,
            noise_seed=int(noise_seed) + i,
            embed_max_length=embed_max_length,
            keyword_embed_max_length=keyword_embed_max_length,
            num_steps=num_steps,
            sequence_beam_width=sequence_beam_width,
            min_length=min_length,
            max_length=max_length,
            joint_opt_steps=joint_opt_steps,
            joint_opt_lr=joint_opt_lr,
        )
        sentence_results.append(result)

    parts = [r.anonymized_text.strip() for r in sentence_results if r.anonymized_text.strip()]
    combined = ". ".join(parts)
    return SentenceWiseAnonymizationResult(
        anonymized_text=combined,
        sentence_results=sentence_results,
        source_sentences=source_sentences,
    )


# =========================
# Paraphrasing pipeline
# =========================


def load_paraphraser_model(
    model_name: str,
    device: str,
    *,
    cache_dir: Optional[str] = None,
) -> Tuple[Any, Any, str]:
    """
    Load paraphraser as seq2seq if available; otherwise fallback to causal LM.
    """

    tokenizer = AutoTokenizer.from_pretrained(model_name, cache_dir=cache_dir)
    if tokenizer.pad_token is None and tokenizer.eos_token is not None:
        tokenizer.pad_token = tokenizer.eos_token

    try:
        model = AutoModelForSeq2SeqLM.from_pretrained(model_name, cache_dir=cache_dir).to(device).eval()
        return tokenizer, model, "seq2seq"
    except Exception:
        model = AutoModelForCausalLM.from_pretrained(model_name, cache_dir=cache_dir).to(device).eval()
        if model.config.pad_token_id is None and tokenizer.pad_token_id is not None:
            model.config.pad_token_id = tokenizer.pad_token_id
        return tokenizer, model, "causal"


def load_paraphraser_model_with_fallback(
    model_name: str,
    fallback_models: List[str],
    device: str,
    *,
    cache_dir: Optional[str] = None,
) -> Tuple[Any, Any, str, str]:
    """Try primary paraphraser model first, then fallback model list."""

    candidates: List[str] = []
    for name in [model_name] + list(fallback_models):
        if name and name not in candidates:
            candidates.append(name)

    last_error: Optional[Exception] = None
    for i, candidate in enumerate(candidates, start=1):
        print(f"Paraphraser candidate [{i}/{len(candidates)}]: {candidate}")
        try:
            tokenizer, model, model_type = load_paraphraser_model(
                candidate,
                device,
                cache_dir=cache_dir,
            )
            if candidate != model_name:
                print(f"Falling back from {model_name} to {candidate}.")
            return tokenizer, model, model_type, candidate
        except Exception as exc:  # noqa: BLE001
            last_error = exc
            print(f"Could not load {candidate}: {exc}")

    raise RuntimeError("Failed to load paraphrase model and all fallbacks.") from last_error


def ollama_generate(
    *,
    base_url: str,
    model: str,
    prompt: str,
    num_predict: int,
    temperature: float = 0.0,
    timeout_sec: float = 600.0,
) -> str:
    """
    Call a local Ollama server HTTP API (/api/generate).

    Requires Ollama running (e.g. `ollama serve`) and the model pulled (`ollama pull <model>`).
    """

    url = base_url.rstrip("/") + "/api/generate"
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": {
            "num_predict": int(num_predict),
            "temperature": float(temperature),
        },
    }
    data = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout_sec) as response:
            body = json.loads(response.read().decode("utf-8"))
    except urllib.error.URLError as exc:
        raise RuntimeError(
            f"Ollama request failed ({url}). Is Ollama running? Error: {exc}"
        ) from exc

    return str(body.get("response", "")).strip()


def paraphrase_with_ollama(
    text: str,
    *,
    model_name: str,
    fallback_models: List[str],
    ollama_base_url: str,
    max_new_tokens: int,
    paraphrase_by_sentence: bool,
    keywords: Optional[List[str]],
) -> ParaphraseResult:
    """
    Paraphrase via Ollama instead of in-process Hugging Face models.
    Uses instruction-style prompts (same as seq2seq path in build_paraphrase_prompt).
    """

    candidates: List[str] = []
    for name in [model_name] + list(fallback_models):
        if name and name not in candidates:
            candidates.append(name)

    last_error: Optional[Exception] = None
    for i, candidate in enumerate(candidates, start=1):
        print(f"Ollama paraphrase candidate [{i}/{len(candidates)}]: {candidate}")
        try:
            source_chunks = split_sentences_by_period(text) if paraphrase_by_sentence else [text]
            if len(source_chunks) == 0:
                source_chunks = [text]

            paraphrased_chunks: List[str] = []
            for chunk in source_chunks:
                sentence_count_hint = max(1, len(split_sentences_by_period(chunk)))
                prompt = build_paraphrase_prompt(
                    text=chunk,
                    sentence_count_hint=sentence_count_hint,
                    model_type="seq2seq",
                    keywords=keywords,
                )
                first_pass = ollama_generate(
                    base_url=ollama_base_url,
                    model=candidate,
                    prompt=prompt,
                    num_predict=max_new_tokens,
                    temperature=0.0,
                )
                if violates_local_rewrite_constraints(chunk, first_pass, keywords=keywords):
                    second_pass = ollama_generate(
                        base_url=ollama_base_url,
                        model=candidate,
                        prompt=prompt,
                        num_predict=max_new_tokens,
                        temperature=0.85,
                    )
                    final_chunk = (
                        second_pass
                        if not violates_local_rewrite_constraints(
                            chunk,
                            second_pass,
                            keywords=keywords,
                        )
                        else render_fallback_summary(chunk, keywords=keywords)
                    )
                else:
                    final_chunk = first_pass
                paraphrased_chunks.append(final_chunk.strip())

            paraphrased_text = ". ".join([c for c in paraphrased_chunks if c]).strip()
            if not paraphrased_text:
                paraphrased_text = text.strip()

            return ParaphraseResult(
                model_name=candidate,
                model_type="ollama",
                input_text=text,
                paraphrased_text=paraphrased_text,
            )
        except Exception as exc:  # noqa: BLE001
            last_error = exc
            print(f"Could not use Ollama model {candidate}: {exc}")

    raise RuntimeError("Failed to paraphrase with Ollama and all fallbacks.") from last_error


def build_paraphrase_prompt(
    text: str,
    sentence_count_hint: int,
    model_type: str,
    keywords: Optional[List[str]] = None,
) -> str:
    """
    Build instruction prompt for constrained local rewriting.
    """

    keyword_line = "Keywords: (none)"
    if keywords:
        keyword_line = f"Approved public keywords to keep if already present: {', '.join(keywords)}"

    if model_type == "seq2seq":
        return (
            "Rewrite the anonymized text below into a short, neutral, locally safe summary. "
            "Preserve placeholders such as [PERSON], [AGE], [ORG], and [LOCATION] exactly. "
            "Do not add names, numbers, organizations, addresses, dates, or locations that are not "
            "already present. Keep approved public keywords only if they are already supported by the "
            f"text. Keep roughly {sentence_count_hint} sentence(s). If the text is degraded, simplify "
            "it instead of inventing missing facts.\n\n"
            f"{keyword_line}\n\nText: {text}"
        )
    return (
        "Rewrite the anonymized text below into a short, neutral, privacy-safe summary. Preserve "
        "placeholders such as [PERSON], [AGE], [ORG], and [LOCATION] exactly. Do not add names, "
        "numbers, organizations, addresses, dates, or locations that are not already present. "
        f"Keep roughly {sentence_count_hint} sentence(s). If the text is degraded, simplify it "
        "instead of inventing facts.\n\n"
        f"{keyword_line}\n\nAnonymized text: {text}\n\nRewritten prompt:"
    )


def is_too_short_or_collapsed(source_text: str, candidate_text: str) -> bool:
    """
    Heuristic guard against severe collapse (e.g. single short sentence summaries).
    """

    if not candidate_text.strip():
        return True
    char_ratio = len(candidate_text.strip()) / max(1, len(source_text.strip()))
    source_sentences = max(1, len(split_sentences_by_period(source_text)))
    candidate_sentences = max(1, len(split_sentences_by_period(candidate_text)))
    if char_ratio < 0.45:
        return True
    if source_sentences >= 3 and candidate_sentences < 2:
        return True
    return False


def has_unapproved_numeric_content(
    source_text: str,
    candidate_text: str,
    keywords: Optional[Sequence[str]] = None,
) -> bool:
    """Reject rewrites that introduce novel numbers not present in the source."""

    source_numbers = set(re.findall(r"\b\d+(?:[.,]\d+)?\b", source_text))
    candidate_numbers = set(re.findall(r"\b\d+(?:[.,]\d+)?\b", candidate_text))
    return not candidate_numbers.issubset(source_numbers)


def has_unapproved_capitalized_entities(
    source_text: str,
    candidate_text: str,
    keywords: Optional[Sequence[str]] = None,
) -> bool:
    """Reject rewrites that invent new entity-like capitalized tokens."""

    allowed = {"I", "UK", "London"}
    for keyword in keywords or []:
        for token in re.findall(r"\b[A-Z][A-Za-z0-9_-]*\b", keyword):
            allowed.add(token)
    for token in re.findall(r"\[[A-Z]+\]", source_text):
        allowed.add(token)
    for token in re.findall(r"\b[A-Z][A-Za-z0-9_-]*\b", source_text):
        allowed.add(token)
    candidate_tokens = set(re.findall(r"\[[A-Z]+\]|\b[A-Z][A-Za-z0-9_-]*\b", candidate_text))
    return any(token not in allowed for token in candidate_tokens)


def leaks_removal_targets(text: str, removal_targets: Sequence[str]) -> bool:
    """Check whether requested removals still appear after a rewrite/removal pass."""

    for target in removal_targets:
        cleaned = target.strip()
        if not cleaned or cleaned.startswith("[") and cleaned.endswith("]"):
            continue
        if re.search(re.escape(cleaned), text, flags=re.IGNORECASE):
            return True
    return False


def violates_local_rewrite_constraints(
    source_text: str,
    candidate_text: str,
    *,
    keywords: Optional[Sequence[str]] = None,
) -> bool:
    """Guard against invented facts in the local rewrite stage."""

    if is_too_short_or_collapsed(source_text, candidate_text):
        return True
    if has_unapproved_numeric_content(source_text, candidate_text, keywords):
        return True
    if has_unapproved_capitalized_entities(source_text, candidate_text, keywords):
        return True
    return False


def build_removal_prompt(
    text: str,
    removal_targets: List[str],
    model_type: str,
    keywords: Optional[List[str]] = None,
) -> str:
    """
    Build prompt for removing additional user-specified information.

    The model is instructed to:
    - remove requested details,
    - keep the rest coherent and human-like,
    - avoid adding new facts,
    - still consider keyword topics where compatible.
    """

    removal_line = ", ".join(removal_targets)
    keyword_line = "Keywords: (none)"
    if keywords:
        keyword_line = f"Keywords to still consider when possible: {', '.join(keywords)}"

    if model_type == "seq2seq":
        return (
            "Revise the text below by replacing the requested information with the matching privacy "
            "placeholders. Preserve all remaining text structure as much as possible. Do not add "
            "new facts, names, numbers, or locations.\n\n"
            f"Information to replace: {removal_line}\n"
            f"{keyword_line}\n\n"
            f"Text: {text}"
        )
    return (
        "Revise the text below by replacing the requested information with matching privacy "
        "placeholders. Preserve all remaining text structure as much as possible. Do not add "
        "new facts, names, numbers, or locations.\n\n"
        f"Information to replace: {removal_line}\n"
        f"{keyword_line}\n\n"
        f"Text: {text}\n\nRevised text:"
    )


@torch.no_grad()
def generate_paraphrase_once(
    *,
    tokenizer: Any,
    model: Any,
    model_type: str,
    text: str,
    device: str,
    max_input_tokens: int,
    max_new_tokens: int,
    num_beams: int,
    do_sample: bool,
    keywords: Optional[List[str]] = None,
) -> str:
    """
    Generate one paraphrase attempt for one text chunk.
    """

    sentence_count_hint = max(1, len(split_sentences_by_period(text)))
    prompt = build_paraphrase_prompt(
        text=text,
        sentence_count_hint=sentence_count_hint,
        model_type=model_type,
        keywords=keywords,
    )
    model_inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=max_input_tokens,
    ).to(device)

    if model_type == "seq2seq":
        outputs = model.generate(
            **model_inputs,
            do_sample=do_sample,
            temperature=0.85 if do_sample else None,
            top_p=0.92 if do_sample else None,
            num_beams=max(1, int(num_beams)) if not do_sample else 1,
            no_repeat_ngram_size=3,
            repetition_penalty=1.05,
            max_new_tokens=max_new_tokens,
            min_new_tokens=max(12, min(64, max_new_tokens // 3)),
            early_stopping=True,
        )
        return tokenizer.decode(outputs[0], skip_special_tokens=True).strip()

    prompt_len = model_inputs["input_ids"].shape[1]
    outputs = model.generate(
        **model_inputs,
        do_sample=do_sample,
        temperature=0.85 if do_sample else None,
        top_p=0.92 if do_sample else None,
        num_beams=max(2, int(num_beams)) if not do_sample else 1,
        no_repeat_ngram_size=3,
        repetition_penalty=1.08,
        max_new_tokens=max_new_tokens,
        min_new_tokens=max(12, min(64, max_new_tokens // 3)),
        early_stopping=True,
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=tokenizer.eos_token_id,
    )
    gen_ids = outputs[0][prompt_len:]
    return tokenizer.decode(gen_ids, skip_special_tokens=True).strip()


def render_fallback_summary(text: str, keywords: Optional[Sequence[str]] = None) -> str:
    """
    Deterministic fallback when local generation is degraded.

    This intentionally avoids inventing new details; it just normalizes the
    scrubbed text into a short stable summary.
    """

    cleaned = normalize_whitespace(text)
    if not cleaned:
        return ""
    chunks = split_sentences_by_period(cleaned)
    if not chunks:
        return cleaned
    limited = " ".join(chunks[:2]).strip()
    return limited


def extract_content_words(text: str) -> List[str]:
    """Return simple content-word tokens for overlap checks."""

    stopwords = {
        "the",
        "and",
        "for",
        "that",
        "with",
        "this",
        "from",
        "into",
        "where",
        "when",
        "have",
        "just",
        "your",
        "after",
        "about",
        "they",
        "them",
        "then",
        "than",
        "there",
        "their",
        "would",
        "could",
        "should",
        "want",
        "need",
        "looking",
        "please",
    }
    words = re.findall(r"\b[a-z]{3,}\b", text.lower())
    return [word for word in words if word not in stopwords]


def lexical_overlap_ratio(source_text: str, candidate_text: str) -> float:
    """Approximate semantic faithfulness with content-word overlap."""

    source_words = set(extract_content_words(source_text))
    candidate_words = set(extract_content_words(candidate_text))
    if not source_words or not candidate_words:
        return 0.0
    return len(source_words & candidate_words) / max(1, len(source_words))


def looks_like_quality_collapse(
    source_text: str,
    candidate_text: str,
    *,
    keywords: Optional[Sequence[str]] = None,
) -> bool:
    """Detect outputs that are fluent-looking but semantically ungrounded."""

    candidate = normalize_whitespace(candidate_text)
    if not candidate:
        return True
    if violates_local_rewrite_constraints(source_text, candidate, keywords=keywords):
        return True
    if ".." in candidate or ";;" in candidate:
        return True
    if lexical_overlap_ratio(source_text, candidate) < 0.2:
        return True
    return False


def select_request_sentence(sentences: Sequence[str]) -> str:
    """Pick the most request-like sentence from scrubbed text."""

    request_markers = ("want", "need", "looking", "recommend", "help", "find", "search")
    for sentence in sentences:
        lowered = sentence.lower()
        if any(marker in lowered for marker in request_markers):
            return sentence.strip()
    return sentences[-1].strip() if sentences else ""


def build_template_fallback_output(
    *,
    preprocessed: PreprocessedPrivacyText,
    keywords: Sequence[str],
    residual_summary: Optional[str] = None,
) -> str:
    """
    Build a deterministic final prompt from scrubbed text and approved public slots.
    """

    del keywords
    summary_text = restore_safe_slot_placeholders(
        residual_summary if residual_summary is not None else preprocessed.scrubbed_text,
        safe_task_keywords=preprocessed.safe_task_keywords,
        safe_location_keywords=preprocessed.safe_location_keywords,
        safe_preference_keywords=preprocessed.safe_preference_keywords,
    )
    sentences = split_sentences_by_period(summary_text)
    context_sentence = sentences[0].strip() if sentences else ""
    request_sentence = select_request_sentence(sentences)
    if request_sentence == context_sentence and len(sentences) > 1:
        request_sentence = sentences[-1].strip()

    parts: List[str] = []
    if context_sentence:
        parts.append(f"Context: {context_sentence}")
    if request_sentence:
        parts.append(f"Request: {request_sentence}")
    if preprocessed.safe_task_keywords:
        parts.append("Task: " + ", ".join(preprocessed.safe_task_keywords))
    if preprocessed.safe_location_keywords:
        parts.append("Location: " + ", ".join(preprocessed.safe_location_keywords))
    if preprocessed.safe_preference_keywords:
        parts.append("Preferences: " + ", ".join(preprocessed.safe_preference_keywords))

    if not parts:
        return summary_text
    return " ".join(parts)


@torch.no_grad()
def paraphrase_with_open_source_llm(
    text: str,
    *,
    model_name: str,
    device: str,
    max_input_tokens: int = 512,
    max_new_tokens: int = 128,
    num_beams: int = 4,
    paraphrase_by_sentence: bool = True,
    fallback_models: Optional[List[str]] = None,
    cache_dir: Optional[str] = None,
    keywords: Optional[List[str]] = None,
    llm_backend: str = "hf",
    ollama_base_url: str = "http://127.0.0.1:11434",
) -> ParaphraseResult:
    """
    Paraphrase anonymized text with an open-source model.

    Strategy:
    - Optionally paraphrase per sentence (default) for better stability.
    - If first deterministic pass is too short/collapsed, retry with sampling.
    - If still poor, keep original chunk.

    llm_backend:
    - "hf": Hugging Face Transformers in-process (downloads weights).
    - "ollama": local Ollama HTTP API (no HF paraphrase download).
    """

    if llm_backend == "ollama":
        return paraphrase_with_ollama(
            text,
            model_name=model_name,
            fallback_models=fallback_models or [],
            ollama_base_url=ollama_base_url,
            max_new_tokens=max_new_tokens,
            paraphrase_by_sentence=paraphrase_by_sentence,
            keywords=keywords,
        )

    tokenizer, model, model_type, loaded_model_name = load_paraphraser_model_with_fallback(
        model_name=model_name,
        fallback_models=fallback_models or [],
        device=device,
        cache_dir=cache_dir,
    )

    source_chunks = split_sentences_by_period(text) if paraphrase_by_sentence else [text]
    if len(source_chunks) == 0:
        source_chunks = [text]

    paraphrased_chunks: List[str] = []
    for chunk in source_chunks:
        first_pass = generate_paraphrase_once(
            tokenizer=tokenizer,
            model=model,
            model_type=model_type,
            text=chunk,
            device=device,
            max_input_tokens=max_input_tokens,
            max_new_tokens=max_new_tokens,
            num_beams=num_beams,
            do_sample=False,
            keywords=keywords,
        )
        if violates_local_rewrite_constraints(chunk, first_pass, keywords=keywords):
            second_pass = generate_paraphrase_once(
                tokenizer=tokenizer,
                model=model,
                model_type=model_type,
                text=chunk,
                device=device,
                max_input_tokens=max_input_tokens,
                max_new_tokens=max_new_tokens,
                num_beams=num_beams,
                do_sample=True,
                keywords=keywords,
            )
            final_chunk = (
                second_pass
                if not violates_local_rewrite_constraints(chunk, second_pass, keywords=keywords)
                else render_fallback_summary(chunk, keywords=keywords)
            )
        else:
            final_chunk = first_pass
        paraphrased_chunks.append(final_chunk.strip())

    paraphrased_text = ". ".join([chunk for chunk in paraphrased_chunks if chunk]).strip()
    if not paraphrased_text:
        paraphrased_text = text.strip()

    return ParaphraseResult(
        model_name=loaded_model_name,
        model_type=model_type,
        input_text=text,
        paraphrased_text=paraphrased_text,
    )


@torch.no_grad()
def remove_information_with_open_source_llm(
    text: str,
    *,
    removal_targets: List[str],
    model_name: str,
    device: str,
    max_input_tokens: int = 512,
    max_new_tokens: int = 128,
    num_beams: int = 4,
    fallback_models: Optional[List[str]] = None,
    cache_dir: Optional[str] = None,
    keywords: Optional[List[str]] = None,
    removal_method: str = "literal",
    llm_backend: str = "hf",
    ollama_base_url: str = "http://127.0.0.1:11434",
) -> ParaphraseResult:
    """
    Remove user-specified information from already-paraphrased text and regenerate output.
    """

    if len(removal_targets) == 0:
        return ParaphraseResult(
            model_name=model_name,
            model_type="unknown",
            input_text=text,
            paraphrased_text=text,
        )

    if removal_method == "literal":
        revised_text = replace_targets_literal(text, removal_targets)
        return ParaphraseResult(
            model_name=model_name,
            model_type="literal",
            input_text=text,
            paraphrased_text=revised_text,
        )

    if removal_method not in {"llm", "literal_then_llm"}:
        raise ValueError(
            "removal_method must be one of: literal, llm, literal_then_llm"
        )

    working_text = text
    if removal_method == "literal_then_llm":
        working_text = replace_targets_literal(text, removal_targets)

    if llm_backend == "ollama":
        candidates: List[str] = []
        for name in [model_name] + list(fallback_models or []):
            if name and name not in candidates:
                candidates.append(name)
        prompt = build_removal_prompt(
            text=working_text,
            removal_targets=removal_targets,
            model_type="seq2seq",
            keywords=keywords,
        )
        last_ollama_error: Optional[Exception] = None
        for i, candidate in enumerate(candidates, start=1):
            print(f"Ollama removal candidate [{i}/{len(candidates)}]: {candidate}")
            try:
                revised_text = ollama_generate(
                    base_url=ollama_base_url,
                    model=candidate,
                    prompt=prompt,
                    num_predict=max_new_tokens,
                    temperature=0.0,
                )
                if not revised_text.strip():
                    revised_text = working_text
                if leaks_removal_targets(revised_text, removal_targets):
                    revised_text = replace_targets_literal(working_text, removal_targets)
                return ParaphraseResult(
                    model_name=candidate,
                    model_type="ollama",
                    input_text=text,
                    paraphrased_text=revised_text.strip(),
                )
            except Exception as exc:  # noqa: BLE001
                last_ollama_error = exc
                print(f"Could not use Ollama model {candidate}: {exc}")
        raise RuntimeError(
            "Failed removal step with Ollama and all fallbacks."
        ) from last_ollama_error

    tokenizer, model, model_type, loaded_model_name = load_paraphraser_model_with_fallback(
        model_name=model_name,
        fallback_models=fallback_models or [],
        device=device,
        cache_dir=cache_dir,
    )

    prompt = build_removal_prompt(
        text=working_text,
        removal_targets=removal_targets,
        model_type=model_type,
        keywords=keywords,
    )
    model_inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=max_input_tokens,
    ).to(device)

    if model_type == "seq2seq":
        outputs = model.generate(
            **model_inputs,
            do_sample=False,
            num_beams=max(1, int(num_beams)),
            no_repeat_ngram_size=3,
            repetition_penalty=1.05,
            max_new_tokens=max_new_tokens,
            min_new_tokens=max(12, min(64, max_new_tokens // 3)),
            early_stopping=True,
        )
        revised_text = tokenizer.decode(outputs[0], skip_special_tokens=True).strip()
    else:
        prompt_len = model_inputs["input_ids"].shape[1]
        outputs = model.generate(
            **model_inputs,
            do_sample=False,
            num_beams=max(2, int(num_beams)),
            no_repeat_ngram_size=3,
            repetition_penalty=1.08,
            max_new_tokens=max_new_tokens,
            min_new_tokens=max(12, min(64, max_new_tokens // 3)),
            early_stopping=True,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )
        gen_ids = outputs[0][prompt_len:]
        revised_text = tokenizer.decode(gen_ids, skip_special_tokens=True).strip()

    if not revised_text:
        revised_text = working_text
    if leaks_removal_targets(revised_text, removal_targets):
        revised_text = replace_targets_literal(working_text, removal_targets)

    return ParaphraseResult(
        model_name=loaded_model_name,
        model_type=model_type,
        input_text=text,
        paraphrased_text=revised_text,
    )


# =========================
# Entry point
# =========================


def build_arg_parser() -> argparse.ArgumentParser:
    """Create and return CLI parser."""

    parser = argparse.ArgumentParser(
        description=(
            "Main pipeline: sentence-wise localized anonymization followed by open-source "
            "paraphrasing into a natural, human-like prompt."
        )
    )

    # Layer 2 controls (least-sensitive information user allows to guide inversion)
    parser.add_argument("-t", "--text", type=str, required=True, help="Private text input.")
    parser.add_argument(
        "-k",
        "--keywords",
        type=str,
        default="",
        help="Comma-separated releasable/non-sensitive keywords used to guide inversion.",
    )

    # Layer 3 controls (unclear sensitivity handled via metric-DP style embedding perturbation)
    parser.add_argument(
        "--sigma",
        type=float,
        default=0.1,
        help="Gaussian noise std for metric-DP style perturbation on sentence embeddings.",
    )
    parser.add_argument(
        "--keyword-total-weight",
        type=float,
        default=0.35,
        help="Total embedding mixture weight assigned to releasable keyword embeddings.",
    )
    parser.add_argument(
        "--dp-delta",
        type=float,
        default=1e-3,
        help="Delta used by the metric-DP privacy accountant (overall epsilon report).",
    )
    parser.add_argument(
        "--dp-sensitivity",
        type=float,
        default=1.0,
        help="Assumed L2 sensitivity for sentence-embedding release in privacy accounting.",
    )
    parser.add_argument(
        "--joint-opt-steps",
        type=int,
        default=80,
        help="Number of steps for joint cosine target optimization.",
    )
    parser.add_argument(
        "--joint-opt-lr",
        type=float,
        default=0.1,
        help="Learning rate for joint cosine target optimization.",
    )
    parser.add_argument(
        "--noise-seed",
        type=int,
        default=0,
        help="Base RNG seed; sentence i uses seed + i.",
    )
    parser.add_argument("--num-steps", type=int, default=40, help="Vec2Text recursive steps.")
    parser.add_argument("--min-length", type=int, default=6, help="Minimum generated token length.")
    parser.add_argument("--max-length", type=int, default=40, help="Maximum generated token length.")

    # Optional model/cache overrides for vec2text
    parser.add_argument(
        "--vec2text-inversion-model",
        type=str,
        default="jxm/gtr__nq__32",
        help="Inversion model checkpoint name.",
    )
    parser.add_argument(
        "--vec2text-corrector-model",
        type=str,
        default="jxm/gtr__nq__32__correct",
        help="Corrector model checkpoint name.",
    )
    parser.add_argument(
        "--vec2text-cache-dir",
        type=str,
        default=None,
        help="Optional cache directory for vec2text model downloads.",
    )

    # Paraphraser parameters
    parser.add_argument(
        "--paraphrase-model",
        type=str,
        default="qwen3.5:latest",
        help=(
            "Primary paraphrase model: Ollama tag (default, e.g. qwen3.5:latest) when "
            "--llm-backend ollama; Hugging Face model id when --llm-backend hf."
        ),
    )
    parser.add_argument(
        "--paraphrase-fallback-models",
        type=str,
        default="",
        help=(
            "Comma-separated fallback models (same family as backend: Ollama tags or HF ids)."
        ),
    )
    parser.add_argument(
        "--paraphrase-max-new-tokens",
        type=int,
        default=128,
        help="Maximum number of generated tokens during paraphrasing.",
    )
    parser.add_argument(
        "--paraphrase-num-beams",
        type=int,
        default=4,
        help="Beam width used for deterministic paraphrase decoding.",
    )
    parser.add_argument(
        "--paraphrase-max-input-tokens",
        type=int,
        default=512,
        help="Tokenizer max input length for paraphrase prompts.",
    )
    parser.add_argument(
        "--paraphrase-by-sentence",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Paraphrase anonymized output sentence-by-sentence (default: true).",
    )
    parser.add_argument(
        "--hf-cache-dir",
        type=str,
        default=None,
        help="Optional Hugging Face cache (vec2text + paraphrase when --llm-backend hf only).",
    )
    parser.add_argument(
        "--llm-backend",
        type=str,
        default="ollama",
        choices=["ollama", "hf"],
        help=(
            "LLM backend for paraphrase/removal: 'ollama' (default) uses local Ollama HTTP; "
            "'hf' loads Hugging Face Transformers in-process for paraphrase."
        ),
    )
    parser.add_argument(
        "--ollama-base-url",
        type=str,
        default="http://127.0.0.1:11434",
        help="Ollama API base URL (used when --llm-backend ollama).",
    )
    parser.add_argument(
        "--remove-info",
        type=str,
        default="",
        help="Layer 1: comma-separated most-sensitive information to remove after paraphrasing.",
    )
    parser.add_argument(
        "--interactive-removal",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Prompt user for additional information to remove after first paraphrase.",
    )
    parser.add_argument(
        "--max-removal-rounds",
        type=int,
        default=3,
        help="Maximum interactive refinement rounds for extra removals.",
    )
    parser.add_argument(
        "--removal-method",
        type=str,
        default="literal",
        choices=["literal", "llm", "literal_then_llm"],
        help=(
            "How to apply final sensitive-info removal: literal replacement only (default), "
            "LLM rewrite, or literal replacement followed by LLM rewrite."
        ),
    )

    # Performance flags
    parser.add_argument(
        "--skip-baseline",
        action="store_true",
        default=False,
        help=(
            "Skip the no-keyword comparison run. Cuts anonymization time nearly in half. "
            "Recommended for production use; omit for research comparisons."
        ),
    )
    parser.add_argument(
        "--max-privacy-chunks",
        type=int,
        default=3,
        help=(
            "Maximum number of residual semantic chunks released under the DP mechanism. "
            "Lower values usually improve privacy accounting and runtime."
        ),
    )
    parser.add_argument(
        "--fast",
        action="store_true",
        default=False,
        help=(
            "Enable fast mode: reduces joint-opt-steps to 40, num-steps to 20, and "
            "paraphrase-num-beams to 2. Implies --skip-baseline. Trades modest quality "
            "for ~3-4x total speedup."
        ),
    )

    return parser


def main() -> None:
    """Execute full anonymize -> paraphrase workflow."""

    args = build_arg_parser().parse_args()
    if args.fast:
        args.skip_baseline = True
        args.joint_opt_steps = min(args.joint_opt_steps, 40)
        args.num_steps = min(args.num_steps, 20)
        args.paraphrase_num_beams = min(args.paraphrase_num_beams, 2)
        args.max_privacy_chunks = min(args.max_privacy_chunks, 2)

    keywords = parse_keyword_list(args.keywords)
    fallback_models = parse_model_list(args.paraphrase_fallback_models)
    initial_removals = parse_removal_list(args.remove_info)

    print("\n--- Sensitive text (private input X) ---")
    print(args.text)
    print("\n--- User-defined non-sensitive keywords ---")
    if keywords:
        for i, keyword in enumerate(keywords, start=1):
            print(f"  {i}. {keyword}")
    else:
        print("  (none — inversion uses noisy E(X) only)")

    preprocessed = preprocess_privacy_text(
        args.text,
        keywords=keywords,
        removal_targets=initial_removals,
        max_privacy_chunks=args.max_privacy_chunks,
    )
    print("\n--- Deterministic privacy scrub (pre-embedding) ---")
    print(preprocessed.scrubbed_text or "(empty after scrub)")
    print("Residual text sent into DP path:", preprocessed.residual_text or "(empty residual)")
    print("Expanded removal targets:", preprocessed.expanded_removal_targets or "(none)")
    print("Preserved public keywords:", preprocessed.preserved_keywords or "(none)")
    print("Residual DP release units:", len(preprocessed.residual_segments))

    patch_transformers_constrained_beamsearch_4372()
    torch.manual_seed(0)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print("\nDevice:", device)

    corrector = load_vec2text_corrector(
        device=device,
        inversion_model_name=args.vec2text_inversion_model,
        corrector_model_name=args.vec2text_corrector_model,
        cache_dir=args.vec2text_cache_dir,
    )

    # Main path: keyword-guided anonymization (used for downstream final output).
    sentence_wise = anonymize_localized_sentence_wise(
        private_text=preprocessed.residual_text,
        keywords=keywords,
        sigma=args.sigma,
        corrector=corrector,
        device=device,
        keyword_total_weight=args.keyword_total_weight,
        joint_opt_steps=args.joint_opt_steps,
        joint_opt_lr=args.joint_opt_lr,
        noise_seed=args.noise_seed,
        num_steps=args.num_steps,
        min_length=args.min_length,
        max_length=args.max_length,
        max_privacy_chunks=args.max_privacy_chunks,
    )

    sentence_wise_no_keywords: Optional[SentenceWiseAnonymizationResult] = None
    if not args.skip_baseline:
        sentence_wise_no_keywords = anonymize_localized_sentence_wise(
            private_text=preprocessed.residual_text,
            keywords=[],
            sigma=args.sigma,
            corrector=corrector,
            device=device,
            keyword_total_weight=args.keyword_total_weight,
            joint_opt_steps=args.joint_opt_steps,
            joint_opt_lr=args.joint_opt_lr,
            noise_seed=args.noise_seed,
            num_steps=args.num_steps,
            min_length=args.min_length,
            max_length=args.max_length,
            max_privacy_chunks=args.max_privacy_chunks,
        )

    accountant = estimate_metric_dp_privacy_cost(
        num_releases=len(sentence_wise.source_sentences),
        sigma=args.sigma,
        delta=args.dp_delta,
        sensitivity=args.dp_sensitivity,
    )

    print("\n--- Per-chunk anonymized (before join) ---")
    if sentence_wise_no_keywords is None:
        for i, (src, result_kw) in enumerate(
            zip(sentence_wise.source_sentences, sentence_wise.sentence_results),
            start=1,
        ):
            print(f"  [{i}] (source) {src}")
            print(f"      (with keywords)    {result_kw.anonymized_text.strip()}")
    else:
        for i, (src, result_kw, result_no_kw) in enumerate(
            zip(
                sentence_wise.source_sentences,
                sentence_wise.sentence_results,
                sentence_wise_no_keywords.sentence_results,
            ),
            start=1,
        ):
            print(f"  [{i}] (source) {src}")
            print(f"      (with keywords)    {result_kw.anonymized_text.strip()}")
            print(f"      (without keywords) {result_no_kw.anonymized_text.strip()}")

    print("\n--- Anonymized output (combined, with keywords) ---")
    print(sentence_wise.anonymized_text)
    if sentence_wise_no_keywords is not None:
        print("\n--- Baseline output (combined, without keywords) ---")
        print(sentence_wise_no_keywords.anonymized_text)
    print("\n--- Metric-DP privacy accountant (zCDP -> (epsilon, delta)-DP) ---")
    print("  scope: residual ambiguous content only")
    print("  deterministic scrub outside DP:", bool(preprocessed.expanded_removal_targets))
    print("  preserved public keywords outside DP:", bool(preprocessed.preserved_keywords))
    print("  num_releases (residual chunks):", accountant.num_releases)
    print("  sigma:", accountant.sigma)
    print("  sensitivity:", accountant.sensitivity)
    print("  delta:", accountant.delta)
    print("  rho_single:", accountant.rho_single)
    print("  rho_total:", accountant.rho_total)
    print("  epsilon_estimate:", accountant.epsilon)
    if accountant.epsilon > 10:
        print("  warning: epsilon > 10, which is a weak privacy regime for the residual release.")

    print("\nLLM backend for paraphrase/removal:", args.llm_backend)
    print("Primary paraphrase/removal model:", args.paraphrase_model)
    if fallback_models:
        print("Fallback models:", fallback_models)
    if args.llm_backend == "hf" and args.hf_cache_dir:
        print("Hugging Face cache dir:", args.hf_cache_dir)
    if args.llm_backend == "ollama":
        print("Ollama base URL:", args.ollama_base_url)

    paraphrase_result = paraphrase_with_open_source_llm(
        sentence_wise.anonymized_text,
        model_name=args.paraphrase_model,
        device=device,
        max_input_tokens=args.paraphrase_max_input_tokens,
        max_new_tokens=args.paraphrase_max_new_tokens,
        num_beams=args.paraphrase_num_beams,
        paraphrase_by_sentence=args.paraphrase_by_sentence,
        fallback_models=fallback_models,
        cache_dir=args.hf_cache_dir,
        keywords=keywords,
        llm_backend=args.llm_backend,
        ollama_base_url=args.ollama_base_url,
    )

    print("\n--- Paraphrased output (human-like prompt style) ---")
    print(paraphrase_result.paraphrased_text)
    print("\nParaphrase model details:")
    print("  model_name:", paraphrase_result.model_name)
    print("  model_type:", paraphrase_result.model_type)

    refined_output = paraphrase_result.paraphrased_text
    current_model_name = paraphrase_result.model_name

    # Optional one-shot removal from CLI argument.
    if initial_removals:
        print("\n--- Post-paraphrase refinement: removing requested information ---")
        print("Targets:", preprocessed.expanded_removal_targets)
        removal_result = remove_information_with_open_source_llm(
            refined_output,
            removal_targets=preprocessed.expanded_removal_targets,
            model_name=current_model_name,
            device=device,
            max_input_tokens=args.paraphrase_max_input_tokens,
            max_new_tokens=args.paraphrase_max_new_tokens,
            num_beams=args.paraphrase_num_beams,
            fallback_models=fallback_models,
            cache_dir=args.hf_cache_dir,
            keywords=keywords,
            removal_method=args.removal_method,
            llm_backend=args.llm_backend,
            ollama_base_url=args.ollama_base_url,
        )
        refined_output = removal_result.paraphrased_text
        current_model_name = removal_result.model_name
        print("\n--- Updated output after removal request ---")
        print(refined_output)

    # Interactive additional removal loop.
    if args.interactive_removal:
        rounds = max(0, int(args.max_removal_rounds))
        for round_idx in range(rounds):
            try:
                user_input = input(
                    "\nEnter extra information to remove (comma-separated), "
                    "or press Enter to finish: "
                ).strip()
            except EOFError:
                # Non-interactive shell/session.
                break

            if not user_input:
                break

            removal_targets = parse_removal_list(user_input)
            if not removal_targets:
                continue

            print(f"\n--- Interactive removal round {round_idx + 1} ---")
            print("Targets:", removal_targets)
            removal_result = remove_information_with_open_source_llm(
                refined_output,
                removal_targets=removal_targets,
                model_name=current_model_name,
                device=device,
                max_input_tokens=args.paraphrase_max_input_tokens,
                max_new_tokens=args.paraphrase_max_new_tokens,
                num_beams=args.paraphrase_num_beams,
                fallback_models=fallback_models,
                cache_dir=args.hf_cache_dir,
                keywords=keywords,
                removal_method=args.removal_method,
                llm_backend=args.llm_backend,
                ollama_base_url=args.ollama_base_url,
            )
            refined_output = removal_result.paraphrased_text
            current_model_name = removal_result.model_name
            print("\n--- Updated output ---")
            print(refined_output)

    if looks_like_quality_collapse(
        preprocessed.residual_text,
        refined_output,
        keywords=keywords,
    ):
        refined_output = render_fallback_summary(preprocessed.residual_text, keywords=keywords)
        print("\n--- Residual summary fallback output ---")
        print(refined_output)

    final_output = build_template_fallback_output(
        preprocessed=preprocessed,
        keywords=keywords,
        residual_summary=refined_output,
    )
    print("\n--- Structured final output ---")
    print(final_output)

    print("\n--- Final output after optional removals ---")
    print(final_output)

    print("\n--- Per-chunk embedding checks (side-by-side) ---")
    keyword_eval_embs: Optional[torch.Tensor] = None
    if keywords:
        keyword_eval_embs = embed_texts(
            corrector,
            keywords,
            max_length=32,
            device=device,
        )
    comparison_pairs = (
        zip(sentence_wise.sentence_results, sentence_wise_no_keywords.sentence_results)
        if sentence_wise_no_keywords is not None
        else ((result_kw, result_kw) for result_kw in sentence_wise.sentence_results)
    )
    for i, (result_kw, result_no_kw) in enumerate(comparison_pairs, start=1):
        recovered_kw = embed_texts(
            corrector,
            [result_kw.anonymized_text],
            max_length=128,
            device=device,
        )
        recovered_no_kw = embed_texts(
            corrector,
            [result_no_kw.anonymized_text],
            max_length=128,
            device=device,
        )
        clean_ref = result_kw.clean_embedding.to(device)
        cos_kw = cosine_sim(recovered_kw, clean_ref)
        cos_no_kw = cosine_sim(recovered_no_kw, clean_ref)
        print(
            f"  [{i}] cos(recovered, clean E(sentence)) "
            f"with_kw / without_kw = {cos_kw:.4f} / {cos_no_kw:.4f}"
        )
        if keyword_eval_embs is not None:
            kw_mean_with, kw_max_with = cos_to_keywords(
                recovered_kw,
                keyword_eval_embs,
            )
            kw_mean_no, kw_max_no = cos_to_keywords(
                recovered_no_kw,
                keyword_eval_embs,
            )
            print(
                "       kw_cos_mean/max with_kw / without_kw = "
                f"{kw_mean_with:.4f}/{kw_max_with:.4f} / {kw_mean_no:.4f}/{kw_max_no:.4f}"
            )


if __name__ == "__main__":
    main()
